import './pages/login/login'
import './pages/registration/registration'
import './pages/404/404'
import './pages/500/500'
import './pages/settings/settings'
import './pages/changePassword/changePassword'